name: ds_flutter_gen_core
description: Fork of the Flutter code generator for your assets, fonts, colors, … — Get rid of all String-based APIs. Prefer to use original flutter_gen
version: 5.8.1
homepage: https://github.com/al-tush/flutter_gen

environment:
  sdk: '>=2.17.0 <4.0.0'

version_gen:
  path: lib/

dependencies:
  meta: ^1.7.0
  path: ^1.8.0
  yaml: ^3.0.0
  mime: '>=1.0.0 <3.0.0'
  xml: ^6.0.0
  dartx: ^1.0.0
  color: ^3.0.0
  collection: ^1.15.0
  json_annotation: ^4.4.0
  glob: ^2.0.0

  dart_style: ^2.2.4
  archive: ^3.4.0
  args: ^2.0.0
  pub_semver: ^2.0.0
  vector_graphics_compiler: ^1.1.9
  image_size_getter: ^2.1.2

dev_dependencies:
  lints: any # Ignoring the version to allow editing across SDK versions.
  test: ^1.16.0
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  version_gen: ^1.0.1
