name: ds_flutter_gen
description: Fork of the Flutter code generator for your assets, fonts, colors, … — Get rid of all String-based APIs. Prefer to use original flutter_gen
version: 5.8.3
homepage: https://github.com/al-tush/flutter_gen

environment:
  sdk: '>=2.17.0 <4.0.0'

executables:
  fluttergen: ds_flutter_gen_command

dependencies:
  ds_flutter_gen_core: 5.8.3
  args: ^2.0.0

dev_dependencies:
  lints: any # Ignoring the version to allow editing across SDK versions.
  test: ^1.16.0
  test_process: ^2.0.0
